# Generated by Django 4.1.5 on 2023-01-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=13)),
                ("address", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "birthdate",
                    models.DateField(help_text="Users Birthdate: 'MM/DD/YYYY'"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organization",
                    ),
                ),
            ],
        ),
    ]
