# Generated by Django 4.1.5 on 2023-03-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Enter birthdate in YYYY-MM-DD format', max_length=10),
        ),
    ]
